### ISSUE TITLE
Accept application/json not working - TypeError: ObjectId() is not JSON serializable

### ISSUE THREAD

**Issue by adaofeliz** [ranman/gitshots#19]
When we try to fetch the json, using the HTTP Header Accept: application/json the following error is thrown by the server application.

web_1   | 2015-06-01 22:39:20 [9] [ERROR] Error handling request
web_1   | Traceback (most recent call last):
web_1   |   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
web_1   |     respiter = self.wsgi(environ, resp.start_response)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
web_1   |     return self.wsgi_app(environ, start_response)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
web_1   |     response = self.make_response(self.handle_exception(e))
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
web_1   |     reraise(exc_type, exc_value, tb)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
web_1   |     response = self.full_dispatch_request()
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
web_1   |     rv = self.handle_user_exception(e)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
web_1   |     reraise(exc_type, exc_value, tb)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
web_1   |     rv = self.dispatch_request()
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
web_1   |     return self.view_functions[rule.endpoint](**req.view_args)
web_1   |   File "/usr/src/app/app.py", line 93, in decorated
web_1   |     return f(*args, **kwargs)
web_1   |   File "/usr/src/app/app.py", line 181, in user_profile
web_1   |     return jsonify(items=list(gitshots))
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 238, in jsonify
web_1   |     indent=indent),
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
web_1   |     rv = _json.dumps(obj, **kwargs)
web_1   |   File "/usr/local/lib/python2.7/json/__init__.py", line 250, in dumps
web_1   |     sort_keys=sort_keys, **kw).encode(obj)
web_1   |   File "/usr/local/lib/python2.7/json/encoder.py", line 209, in encode
web_1   |     chunks = list(chunks)
web_1   |   File "/usr/local/lib/python2.7/json/encoder.py", line 434, in _iterencode
web_1   |     for chunk in _iterencode_dict(o, _current_indent_level):
web_1   |   File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
web_1   |     for chunk in chunks:
web_1   |   File "/usr/local/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
web_1   |     for chunk in chunks:
web_1   |   File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
web_1   |     for chunk in chunks:
web_1   |   File "/usr/local/lib/python2.7/json/encoder.py", line 442, in _iterencode
web_1   |     o = _default(o)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 83, in default
web_1   |     return _json.JSONEncoder.default(self, o)
web_1   |   File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
web_1   |     raise TypeError(repr(o) + " is not JSON serializable")
web_1   | TypeError: ObjectId('556ccc933faf5a000ab96420') is not JSON serializable

**Comment by ranman** [comment]
And you're using Flask-pymongo ?

**Comment by adaofeliz** [comment]
Yes. I can try to check it tomorrow. Time to sleep in GMT+1 ;)  I need to make the json response work, so that my front-end friends can work on a new interface for gitshots.

**Comment by adaofeliz** [comment]
BTW - You can reproduce this error easily: curl -Haccept:application/json http://gitshots.com/ranman/

**Comment by ranman** [comment]
ok I put a quick fix in for that. not idea.

**Comment by adaofeliz** [comment]
Perfect! :+1:
