### ISSUE TITLE
Updating PyMongo to 3.0.2

### ISSUE THREAD

**Issue by adaofeliz** [ranman/gitshots#21]
There is a problem when updating PyMongo dependency, similar to: https://jira.mongodb.org/browse/PYTHON-899

Gitshots stacktrace:

web_1   | [2015-06-02 04:23:06 +0000] [13] [ERROR] Exception in worker process:
web_1   | Traceback (most recent call last):
web_1   |   File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
web_1   |     worker.init_process()
web_1   |   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
web_1   |     self.wsgi = self.app.wsgi()
web_1   |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1   |     self.callable = self.load()
web_1   |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
web_1   |     return self.load_wsgiapp()
web_1   |   File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
web_1   |     return util.import_app(self.app_uri)
web_1   |   File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
web_1   |     __import__(module)
web_1   |   File "/usr/src/app/app.py", line 60, in <module>
web_1   |     mongo = PyMongo(app)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask_pymongo/__init__.py", line 97, in __init__
web_1   |     self.init_app(app, config_prefix)
web_1   |   File "/usr/local/lib/python2.7/site-packages/flask_pymongo/__init__.py", line 232, in init_app
web_1   |     cx = connection_cls(*args, **kwargs)
web_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 322, in __init__
web_1   |     username, password, dbase, opts)
web_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/client_options.py", line 108, in __init__
web_1   |     options = dict([validate(opt, val) for opt, val in iteritems(options)])
web_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/common.py", line 425, in validate
web_1   |     value = validator(option, value)
web_1   |   File "/usr/local/lib/python2.7/site-packages/pymongo/common.py", line 100, in raise_config_error
web_1   |     raise ConfigurationError("Unknown option %s" % (key,))
web_1   | ConfigurationError: Unknown option auto_start_request

**Comment by ranman** [comment]
That's an issue with the flask-pymongo implementation, it's fine to leave it on the old driver for now I think -- was there something you wanted to include from the newer drivers?

**Comment by adaofeliz** [comment]
Nop. It was just to keep it updated. It's fine!
